title: "My Podcast Title" # Your Podcast's Title 
description: "A brief description of the podcast." # Your Podcast's Description
itunes_author: "Your Name" # Your Name or Pen-Name
owner_name: "Your Name" # Your NAME or PEN NAME
owner_email: "you@example.com" # Your EMAIL
type: "episodic" # episodic OR serial
explicit_bool: "no" # yes OR no (in lowercase)
itunes_summary: "A brief description of the podcast." # This will match what you write in "description" above
baseurl: "/" # /your-repository-name
url: "https://monicletester.github.io" # your-github-user-name.github.io

theme: null
markdown: kramdown

collections:
  episodes:
    output: true
    permalink: episodes/:title/

defaults:
  - scope:
      path: ""
      type: episodes
    values:
      layout: episode

include:
  - '_episodes/'

plugins:
  - jekyll-feed
