title: "" # Your Podcast's Title 
description: "" # Your Podcast's Description
itunes_author: "" # Your Name or Pen-Name
itunes_summary: {{ site.description }}
baseurl: "/podcast"
url: ""

theme: null
markdown: kramdown

collections:
  episodes:
    output: true
    permalink: episodes/:title/

defaults:
  - scope:
      path: ""
      type: episodes
    values:
      layout: episode

include: # Any files to include that are not already in "_includes"
  - '_episodes/'

plugins:
  - jekyll-feed
