title: "" # Your Podcast's Title 
description: "" # Your Podcast's Description
itunes_author: "" # Your Name or Pen-Name
owner_name: "" # Your NAME or PEN NAME
owner_email: "" # Your EMAIL
type: "" # episodic OR serial (serial means that there is an order in which the podcasts should be listened).
explicit_bool: "" # yes OR no (in lowercase)
itunes_summary: {{ site.description }}
baseurl: "/podcast"
url: ""

remote_theme: pages-themes/minimal@v0.2.0
markdown: kramdown

collections:
  episodes:
    output: true
    permalink: episodes/:title/

defaults:
  - scope:
      path: ""
      type: episodes
    values:
      layout: episode

include: # Any files to include that are not already in "_includes"
  - '_episodes/'

plugins:
  - jekyll-feed
  - jekyll-remote-theme
